### ISSUE TITLE
Circle needs to follow search bar queries

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/COM#21]
Currently, the circle is not updated when a search bar query is done. The only time that a circle should **not** be updated is when clicking on a marker.

**Comment by PhilipGriffith** [comment]
This is still an issue, though the requirements have changed a little. The blue search area should be updated when the user types in an address to be geolocated. It should also be updated when they right-click. It should _not_ be updated when the user searches the data for a provider, nor, as you note, when they select a marker.

**Comment by clintonlunn** [comment]
@PhilipGriffith  Should the center point also be drawn, or was that intentionally removed?

**Comment by clintonlunn** [comment]
This seems to be completed. The blue search area is updated on: 
- right click
- geocoder search

I also added a center point to show the location of either the right click, or the geocoder point. i

It might add value to the map to bind a popup to the center point when the geocoder search is used.

**Comment by PhilipGriffith** [comment]
I would say to remove the point from the search area, both to maintain the same visual display across all tools and to reinforce that the circle is simply enclosing an area rather than a data object in its own right.

Hold off on adding any popups. The only things that should have popups are data points: I think the geocoder should be seen by the user as nothing more than a way of querying the data, if that makes any sense at all.

**Comment by clintonlunn** [comment]
For sure. I'll remove these things today.

**Comment by PhilipGriffith** [comment]
Removed the center point and popup.
