### ISSUE TITLE
Mobile landscape buttons bleed over

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#45]
The text in the Bootstrap button group bleeds over when in the mobile Landscape mode.

**Comment by clintonlunn** [comment]
An interim fix: It does not overflow when the words are shord enough. It was failing before because the words were too long. Looks better now and does not overflow on portraid and landscape of even smallest (iPhone 5/SE) screen. 

I figure it would be acceptable because our filters will probably consist of these "Accepts Insurance" and "Accepts Medicare" filters. 

![image](https://user-images.githubusercontent.com/24685932/59160830-83176c80-8aa8-11e9-9f74-13a8c67a798e.png)


![image](https://user-images.githubusercontent.com/24685932/59160836-ad692a00-8aa8-11e9-938e-905af3144f4d.png)

**Comment by clintonlunn** [comment]
```
<label class="btn btn-garnet text-wrap btn-primary p-2">
								<!-- Ttallahassee insurance -->
								<input type="checkbox" name="options" id="insurance" autocomplete="off">
								Accepts Insurance
							</label>
							<label class="btn btn-garnet text-wrap btn-primary p-2">
								<!-- zipcode 32309/medicare -->
								<input type="checkbox" name="options" id="medicare" autocomplete="off">
								Accepts Medicare
							</label>
```

the padding class (p-2) is forcing this padding. If padding is decreased, it will allow larger words to occupy this space without overflow.

**Comment by PhilipGriffith** [comment]
I would consider this issue irrelevant at this point. lol
