### ISSUE TITLE
Handle selections with CSS, rather than a separate FeatureGroup.

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/COM#50]
This is likely lighter as it simply involves CSS styling through HTML attributes, rather than a Leaflet FeatureGroup for a single marker.

**Comment by clintonlunn** [comment]
I am doing some reading on this so I will paste some resources that I have found. We may be able to reorder the map panes in order to show/hide display of certain points. 

[leaflet map panes documentation](https://leafletjs.com/examples/map-panes/)
[leaflet css point ordering issue (old, but gets at the use of panes in decent detail](https://github.com/Leaflet/Leaflet/issues/1734)

**Comment by PhilipGriffith** [comment]
I think this is no longer a relevant issue.
