### ISSUE TITLE
Chrome - Find Me button - on some machines it doesnt find you

### ISSUE THREAD

**Issue by shodge17** [FREAC/COM#54]
On my desktop if I hit the find me button using Chrome I get the following popup message, "You seem located outside the boundaries of the map".  Firefox handles this OK as do other machines using Chrome.  

I think there is a setting on my local machine that needs to be set, but I do not know what it is.  If it is happening on my machine we MAY see it on others, so it would be ideal to figure out what that setting is so we can somewhere add a FAQ.

**Comment by clintonlunn** [comment]
This seems to be a PC specific case. Email conversation discussed removing the locate button when a user is on a pc. 

I am also thinking that this may be an edge case, as most users will probably be accessing the com map from their personal internet networks rather than a large network like a university network.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shodge17** [comment]
I agree.  lets get the "hide on large screens" ready to go, but not implement it -- just somehow comment it out.  Test a few computers at home and NOT connected to FSU's network and lets see how they do.  If most work, then maybe we will just leave the button on all the time.

**Comment by clintonlunn** [comment]
Completed within [Locate pull request](https://github.com/FREAC/COM/pull/55).
